export const ResumeTooltipMsg = "Click to download resume";
export const KritinUrl = "https://kritin.in";
export const NameIsRequired = "Name is Required";
export const EmailIsRequired = "Email is Required";
export const MessageIsRequierd = "Message is Required";
export const EmailIsNotValid = "Email is not valid";
export const DataSuccessSubmit = "Data successfully submitted";
export const DataErrorSubmit = "Error in submitting data";
export const NetworkError = "Network Error";
